esphome:
  name: czujnik-rack
  friendly_name: Czujnik Rack

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG
  logs:
    component: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_password

ota:
  password: !secret ota_password
  platform: esphome

# Don't forget to set ssid and password in your SECRETS 
wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    
# Enable fallback hotspot (captive portal) in case wifi connection fails
ap:
  ssid: !secret ap_ssid
  password: !secret ap_password

captive_portal:

sensor:
  - platform: dht
    pin: GPIO21
    temperature:
      name: "Temperature Rack"
      id: dht_temperature_rack
    humidity:
      name: "Humidity Rack"
      id: dht_humidity_rack
    update_interval: 180s
# Set less frequent interval if temperature or humidity lacks a digit

# For checking connectivity with HomeAssistant 
  - platform: homeassistant
    id: core_update
    entity_id: update.home_assistant_core_update
    name: "home_assistant_core_update"
    internal: true

# Font has to be added to /homeassistant/esphome folder, in this case Arial font
font:
  - file: 'arial.ttf'
    id: font1
    size: 11

  - file: 'arial.ttf'
    id: font2
    size: 21

  - file: 'arial.ttf'
    id: font3
    size: 26

  - file: 'arial.ttf'
    id: font4
    size: 8

time:
  - platform: homeassistant
    id: esptime

i2c:
  sda: GPIO18
  scl: GPIO19
  scan: false

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    lambda: |-

      // Print "Czujnik Rack" in top center.
      it.printf(38, 0, id(font1), TextAlign::TOP_CENTER, "Czujnik Rack");

      // Print time in HH:MM format
      it.strftime(89, 0, id(font1), TextAlign::TOP_CENTER, "%H:%M", id(esptime).now());

      // Print dht_humidity_rackk (from dht sensor)
      if (id(dht_humidity_rack).has_state()) {
        it.printf(60, 64, id(font2), TextAlign::BASELINE_CENTER, "%.0f%%", id(dht_humidity_rack).state);
      } else {
        it.printf(60, 64, id(font2), TextAlign::BASELINE_CENTER, "Error");
      }

      // Print dht_temperature_rack (from dht sensor)
      if (id(dht_temperature_rack).has_state()) {
        it.printf(60, 35, id(font2), TextAlign::BASELINE_CENTER, "%.1f°C", id(dht_temperature_rack).state);
      } else {
        it.printf(60, 35, id(font2), TextAlign::BASELINE_CENTER, "Error");
      }      

      // Print signal (from homeassistant sensor)
      if (id(core_update).has_state()) {
        it.printf(118, 0, id(font4), TextAlign::TOP_CENTER, "((o))");
      } else {
        it.printf(118, 0, id(font4), TextAlign::TOP_CENTER, "I");
      }
